{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecret }}
  labels:
    {{- include "retryshield.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresConnectionString: {{ .Values.secrets.data.postgresConnectionString | quote }}
  redisConnectionString: {{ .Values.secrets.data.redisConnectionString | quote }}
  encryptionKeyBase64: {{ .Values.secrets.data.encryptionKeyBase64 | quote }}
  adminBearerToken: {{ .Values.secrets.data.adminBearerToken | quote }}
{{- end }}
